### ISSUE TITLE
How to change label position?

### ISSUE THREAD

**Issue by dendifz** [jaikeerthick/Composable-Graphs#7]
Can I change the label position from right to left??
![image](https://user-images.githubusercontent.com/81274723/207785763-dfbc1b15-0a5e-4bae-8bd9-64e5100602de.png)

**Comment by jaikeerthick** [comment]
@dendifz  As of now, this feature isn't there. It'll be added in the next version. You can expect this feature really soon by today or tomorrow. Thanks for mentioning !

**Comment by dendifz** [comment]
> @dendifz As of now, this feature isn't there. It'll be added in the next version. You can expect this feature really soon. Thanks for mentioning !

Hello, where is the update?

**Comment by jaikeerthick** [comment]
Hey @dendifz sorry for the delay. The feature is now available in the latest release `v1.2.1`. Please update the library ❤️
